from .enrolment_analysis import get_state_enrolment_stats, get_age_group_distribution
from .demographic_update_analysis import rank_districts_by_updates, analyze_demo_vs_enrolment
from .biometric_update_analysis import analyze_mandatory_update_lag
from .migration_analysis import calculate_migration_score, identify_migration_corridors
